Add first try of private add, fixes and shellcheckrc

diff --git a/risks b/risks
--- a/risks
+++ b/risks
@@ -1146,6 +1146,7 @@ risks_private_usage() {
   printf "Commands:\n"
   echo "  import   Import the GPG private key from the backup to the GPG keyring, in read-write mode"
   echo "  remove   Remove the GPG private key from the keyring, and set the hush in read-only mode"
+  echo "  add      Add a key to one of the cryptographic stores"
   echo
 
   # :command.long_usage
@@ -1227,6 +1228,65 @@ risks_private_remove_usage() {
     # :command.usage_fixed_flags
     echo "  --help, -h"
     printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+risks_private_add_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "risks private add - Add a key to one of the cryptographic stores\n"
+    echo
+
+  else
+    printf "risks private add - Add a key to one of the cryptographic stores\n"
+    echo
+
+  fi
+
+  printf "Usage:\n"
+  printf "  risks private add STORE [EXPIRY_DATE] [options]\n"
+  printf "  risks private add --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "Options:\n"
+
+    # :command.usage_fixed_flags
+    echo "  --help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_flags
+    # :flag.usage
+    echo "  --algo, -a"
+    printf "    Key algorithm to use\n"
+    echo
+
+    # :flag.usage
+    echo "  --sign, -S"
+    printf "    If generated key is a GPG subkey, add sign capability\n"
+    echo
+
+    # :flag.usage
+    echo "  --encrypt, -E"
+    printf "    If generated key is a GPG subkey, add encrypt capability\n"
+    echo
+
+    # :command.usage_args
+    printf "Arguments:\n"
+
+    # :argument.usage
+    echo "  STORE"
+    printf "    The key/store type to add\n"
+    printf "    Allowed: gpg, ssh\n"
+    echo
+
+    # :argument.usage
+    echo "  EXPIRY_DATE"
+    printf "    The expiry date for the key, if GPG\n"
     echo
 
   fi
@@ -2725,6 +2785,43 @@ cleanup_gpg_init()
     rm -rf "$tmp_dir"
 }
 
+# utility function only compatibly with "private add gpg" command.
+# Generates the subkeys depending on which parameters are passed.
+generate_subkeys ()
+
+{
+    local algo="${1}"
+    local email="${2}"
+    local expiry="${3}"
+    local expiry_date fingerprint
+
+    expiry_date="$(date +"%Y-%m-%d" --date="${expiry}")"
+
+    fingerprint=$(gpg -K "${email}" | grep fingerprint | head -n 1 | cut -d= -f2 | sed 's/ //g')
+    _message "Fingerprint: ${fingerprint}"
+
+    local gpg_base_cmd=(gpg --pinentry-mode loopback --batch --no-tty --yes --passphrase-fd 0 --quick-add-key "${fingerprint}")
+
+    # Signing subkey
+    if [[ "${args[--sign]}" -eq 1 ]]; then
+        _message "Generating signature subkey-pair"
+        echo "$GPG_PASS" | _run "${gpg_base_cmd[@]}" "${algo}" sign "${expiry_date}" &> /dev/null
+        _catch "Failed to generate subkey-pair"
+    fi
+
+    # Encryption subkey
+
+    if [[ "${args[--encr]}" -eq 1 ]]; then
+        if [[ "${algo}" == "ed25519" ]]; then
+            algo="cv25519"
+        fi
+        _message "Generating encryption subkey-pair"
+        echo "$GPG_PASS" | _run "${gpg_base_cmd[@]}" "${algo}" encr "${expiry_date}" &> /dev/null
+        _catch "Failed to generate subkey-pair"
+    fi
+
+}
+
 # is_gpg_passphrase_cached returns 0 if the
 
 # gpg-agent has the private cached, or 1 if not.
@@ -2741,6 +2838,23 @@ is_gpg_passphrase_cached ()
 
     # Just in case
     return 1
+}
+
+# get_master_key_status returns true if the master private
+
+# GPG key is present in the keyring, or false if it's absent.
+get_master_key_status () {
+    local key_status masterkey_available
+
+    key_status="$(gpg --list-secret-keys | head -n 3 | tail -n 1 | awk '{print $1;}')"
+
+    if [[ "${key_status}" == "pub" ]]; then
+        masterkey_available=true
+    elif [[ "${key_status}" == "sec#" ]]; then
+        masterkey_available=false
+    fi
+
+    print "${masterkey_available}"
 }
 
 # src/lib/graveyard.sh
@@ -2947,7 +3061,7 @@ _get_mail ()
     local name="$1"
     local email="$2"
 
-    [[ -n "${email}" ]] && return
+    [[ -n "${email}" ]] && print "${email}" && return
 
     email="${args[--mail]}"
     [[ -n "${email}" ]] && print "${name}@${email}"
@@ -2961,7 +3075,7 @@ _get_expiry ()
     local expiry
 
     if [[ -z "${1}" ]]; then
-        expiry="0"
+        expiry="never"
     else
         expiry="${1}"
     fi
@@ -5107,7 +5221,11 @@ risks_private_remove_command() {
 
   _set_identity "${args[identity]}"
 
-  # Hush and identity checks
+  # Backup/hush and identity checks
+  # if ! is_luks_mapper_present "$BACKUP_MAPPER" ; then
+  #     _failure "No mounted backup medium found. Mount one with 'risks backup mount </dev/device>'"
+  # fi
+  #
   if ! is_hush_mounted ; then
       _failure "The hush device is not mounted. Mount it first and rerun the command."
   fi
@@ -5149,6 +5267,94 @@ risks_private_remove_command() {
   risks_hush_ro_command
 
   _message "Removed private key from keyring"
+
+}
+
+# :command.function
+risks_private_add_command() {
+  # src/private_add_command.sh
+  echo "# this file is located in 'src/private_add_command.sh'"
+  echo "# code for 'risks private add' goes here"
+  echo "# you can edit it freely and regenerate (it will not be overwritten)"
+  inspect_args
+
+  local masterkey_available email uid
+  local key_type ssh_key_name   # SSH parameters
+  local key_algo expiry         # GPG parameters
+
+  #
+  # Hush and identity checks
+  if ! is_hush_mounted ; then
+      _failure "The hush device is not mounted. Mount it first and rerun the command."
+  fi
+
+  _set_identity ""
+
+  if ! _identity_active ; then
+      _failure "This command requires an identity to be active"
+  fi
+
+  key_algo="${args[--algo]-ed25519}"
+  uid=$(gpg -K | grep uid | head -n 1)
+  email=$(echo "$uid" | grep -E -o "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b")
+  expiry="$(_get_expiry "${args[expiry_date]}")"
+
+  # If GPG, need access to GPG tomb, or verify that the master private key is in ring.
+  if [[ "${args[store]}" == "gpg" ]]; then
+      masterkey_available="$(get_master_key_status)"
+
+      if [[ "${args[--sign]}" -eq 0 ]] && [[ "${args[--encr]}" -eq 0 ]]; then
+          _failure "You must specify either or both of --sign and --encr flags for GPG subkeys"
+      fi
+  fi
+
+  # If SSH ===
+  if [[ "${args[store]}" == "ssh" ]]; then
+      _message "Generating SSH keypair"
+      _message "Type: ${args[--algo]}"
+
+      _run open_tomb "$SSH_TOMB_LABEL" "$IDENTITY"
+
+      # Generate SSH key.
+      _verbose "Generating keys for identity"
+      _run ssh-keygen -t "${key_type}" -b 4096 -C "$email" -N "" -f "${HOME}"/.ssh/"${ssh_key_name}" # No passphrase
+      _verbose "Making keys immutable"
+      sudo chattr +i "${HOME}"/.ssh/"${ssh_key_name}"*
+
+      # Close tomb if was closed and return
+      _run close_tomb "$SSH_TOMB_LABEL" "$IDENTITY"
+
+      _message "Successfully generated new SSH keypair" && return
+  fi
+
+  # If GPG ===
+  if [[ "${args[store]}" == "gpg" ]]; then
+      _message "Generating GPG subkey"
+      _message "Type: ${args[--algo]}"
+      _message "Signing: ${args[--sign]} | Encrypting: ${args[--encrypt]}"
+
+      risks_hush_rw_command
+
+      # Check master private in ring,
+      # If not, open tomb and import master key
+      if [[ $masterkey_available != true ]]; then
+          _message "No master key in keyring, importing from tomb"
+          risks_private_import_command
+      fi
+
+      # Generate keys
+      generate_subkeys "${key_algo}" "${email}" "${expiry}"
+
+      # Remove master key if was imported
+      if [[ $masterkey_available != true ]]; then
+          _message "Removing master private key from keyring"
+          risks_private_remove_command
+      fi
+
+      risks_hush_ro_command
+
+      _message "Successfully generated GPG subkey(s)" && return
+  fi
 
 }
 
@@ -7155,6 +7361,13 @@ risks_private_parse_requirements() {
     shift $#
     ;;
 
+  add )
+    action="add"
+    shift
+    risks_private_add_parse_requirements "$@"
+    shift $#
+    ;;
+
   # :command.command_fallback
   "" )
     risks_private_usage
@@ -7288,6 +7501,89 @@ risks_private_remove_parse_requirements() {
 
     esac
   done
+
+}
+
+# :command.parse_requirements
+risks_private_add_parse_requirements() {
+  # :command.fixed_flags_filter
+  case "${1:-}" in
+  --help | -h )
+    long_usage=yes
+    risks_private_add_usage
+    exit
+    ;;
+
+  esac
+
+  # :command.command_filter
+  action="private add"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+    # :flag.case
+    --algo | -a )
+
+      # :flag.case_no_arg
+      args[--algo]=1
+      shift
+      ;;
+
+    # :flag.case
+    --sign | -S )
+
+      # :flag.case_no_arg
+      args[--sign]=1
+      shift
+      ;;
+
+    # :flag.case
+    --encrypt | -E )
+
+      # :flag.case_no_arg
+      args[--encrypt]=1
+      shift
+      ;;
+
+    -?* )
+      printf "invalid option: %s\n" "$key"
+      exit 1
+      ;;
+
+    * )
+      # :command.parse_requirements_case
+      # :command.parse_requirements_case_simple
+      if [[ -z ${args[store]+x} ]]; then
+
+        args[store]=$1
+        shift
+      elif [[ -z ${args[expiry_date]+x} ]]; then
+
+        args[expiry_date]=$1
+        shift
+      else
+        printf "invalid argument: %s\n" "$key"
+        exit 1
+      fi
+
+      ;;
+
+    esac
+  done
+
+  # :command.required_args_filter
+  if [[ -z ${args[store]+x} ]]; then
+    printf "missing required argument: STORE\nusage: risks private add STORE [EXPIRY_DATE] [options]\n"
+    exit 1
+  fi
+
+  # :command.whitelist_filter
+  if [[ ! ${args[store]} =~ ^(gpg|ssh)$ ]]; then
+    printf "%s\n" "store must be one of: gpg, ssh"
+    exit 1
+  fi
 
 }
 
@@ -8667,6 +8963,14 @@ run() {
       risks_private_remove_usage
     else
       risks_private_remove_command
+    fi
+
+  elif [[ $action == "private add" ]]; then
+    if [[ ${args[--help]:-} ]]; then
+      long_usage=yes
+      risks_private_add_usage
+    else
+      risks_private_add_command
     fi
 
   elif [[ $action == "load" ]]; then
